version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Ops@123456
      - ACCEPT_EULA=Y
    ports:
      - 8002:1433
    volumes:
      - ./data-protection:/root/.aspnet/DataProtection-Keys
    networks:
      - app-network

  taskmanageh.webservice:
    image: ${DOCKER_REGISTRY-}taskmanagehwebservice
    build:
      context: .
      dockerfile: TaskManageH.WebService/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=TaskManageH_2024;User Id=sa;Password=Ops@123456;Trusted_Connection=True;
    networks:
      - app-network

networks:
  app-network:
    driver: bridge